#ChipScope Core Inserter Project File Version 3.0
#Sat Apr 01 11:36:33 CST 2017
Project.device.designInputFile=E\:\\Hardware\\About-Hardware\\Documents\\Code\\ISE14.3-Project\\JS1\\JS\\top_cs.ngc
Project.device.designOutputFile=E\:\\Hardware\\About-Hardware\\Documents\\Code\\ISE14.3-Project\\JS1\\JS\\top_cs.ngc
Project.device.deviceFamily=6
Project.device.enableRPMs=true
Project.device.outputDirectory=E\:\\Hardware\\About-Hardware\\Documents\\Code\\ISE14.3-Project\\JS1\\JS\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=1
Project.filter<0>=
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=SAA7113_decode_uut/your_instance_name clka
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataDepth=1024
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=8
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=SAA7113_decode_uut/your_instance_name dina<0>
Project.unit<0>.triggerChannel<0><1>=SAA7113_decode_uut/your_instance_name dina<1>
Project.unit<0>.triggerChannel<0><2>=SAA7113_decode_uut/your_instance_name dina<2>
Project.unit<0>.triggerChannel<0><3>=SAA7113_decode_uut/your_instance_name dina<3>
Project.unit<0>.triggerChannel<0><4>=SAA7113_decode_uut/your_instance_name dina<4>
Project.unit<0>.triggerChannel<0><5>=SAA7113_decode_uut/your_instance_name dina<5>
Project.unit<0>.triggerChannel<0><6>=SAA7113_decode_uut/your_instance_name dina<6>
Project.unit<0>.triggerChannel<0><7>=SAA7113_decode_uut/your_instance_name dina<7>
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortIsData<1>=true
Project.unit<0>.triggerPortWidth<0>=8
Project.unit<0>.triggerPortWidth<1>=8
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
