[COREGEN.VERILOG Component Instantiation.divider_ip]
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="divider_ip YourInstanceName ("
text007="    .dividend(dividend),"
text008="    .divisor(divisor),"
text009="    .quot(quot),"
text010="    .remd(remd),"
text011="    .clk(clk),"
text012="    .rfd(rfd),"
text013="    .aclr(aclr),"
text014="    .sclr(sclr),"
text015="    .ce(ce));"
text016=""
text017=" "
type=template
[COREGEN.VERILOG Component Instantiation.dpram]
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="dpram YourInstanceName ("
text007="    .addra(addra),"
text008="    .addrb(addrb),"
text009="    .clka(clka),"
text010="    .clkb(clkb),"
text011="    .dina(dina),"
text012="    .doutb(doutb),"
text013="    .ena(ena),"
text014="    .enb(enb),"
text015="    .wea(wea));"
text016=""
text017=" "
type=template
[COREGEN.VERILOG Component Instantiation.hist_ram]
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="hist_ram YourInstanceName ("
text007="    .addr(addr),"
text008="    .clk(clk),"
text009="    .din(din),"
text010="    .dout(dout),"
text011="    .en(en),"
text012="    .we(we));"
text013=""
text014=" "
type=template
[COREGEN.VERILOG Component Instantiation.new_gray_table]
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="new_gray_table YourInstanceName ("
text007="    .addra(addra),"
text008="    .addrb(addrb),"
text009="    .clka(clka),"
text010="    .clkb(clkb),"
text011="    .dina(dina),"
text012="    .doutb(doutb),"
text013="    .wea(wea));"
text014=""
text015=" "
type=template
[COREGEN.VHDL Component Instantiation.divider_ip]
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component divider_ip"
text005="    port ("
text006="    dividend: IN std_logic_VECTOR(31 downto 0);"
text007="    divisor: IN std_logic_VECTOR(19 downto 0);"
text008="    quot: OUT std_logic_VECTOR(31 downto 0);"
text009="    remd: OUT std_logic_VECTOR(19 downto 0);"
text010="    clk: IN std_logic;"
text011="    rfd: OUT std_logic;"
text012="    aclr: IN std_logic;"
text013="    sclr: IN std_logic;"
text014="    ce: IN std_logic);"
text015="end component;"
text016=""
text017=""
text018=""
text019=" "
text020="-------------------------------------------------------------"
text021=" "
text022="-- The following code must appear in the VHDL architecture body."
text023="-- Substitute your own instance name and net names."
text024=" "
text025="your_instance_name : divider_ip"
text026="        port map ("
text027="            dividend => dividend,"
text028="            divisor => divisor,"
text029="            quot => quot,"
text030="            remd => remd,"
text031="            clk => clk,"
text032="            rfd => rfd,"
text033="            aclr => aclr,"
text034="            sclr => sclr,"
text035="            ce => ce);"
text036=" "
type=template
[COREGEN.VHDL Component Instantiation.dpram]
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component dpram"
text005="    port ("
text006="    addra: IN std_logic_VECTOR(15 downto 0);"
text007="    addrb: IN std_logic_VECTOR(12 downto 0);"
text008="    clka: IN std_logic;"
text009="    clkb: IN std_logic;"
text010="    dina: IN std_logic_VECTOR(7 downto 0);"
text011="    doutb: OUT std_logic_VECTOR(63 downto 0);"
text012="    ena: IN std_logic;"
text013="    enb: IN std_logic;"
text014="    wea: IN std_logic);"
text015="end component;"
text016=""
text017=""
text018=""
text019=" "
text020="-------------------------------------------------------------"
text021=" "
text022="-- The following code must appear in the VHDL architecture body."
text023="-- Substitute your own instance name and net names."
text024=" "
text025="your_instance_name : dpram"
text026="        port map ("
text027="            addra => addra,"
text028="            addrb => addrb,"
text029="            clka => clka,"
text030="            clkb => clkb,"
text031="            dina => dina,"
text032="            doutb => doutb,"
text033="            ena => ena,"
text034="            enb => enb,"
text035="            wea => wea);"
text036=" "
type=template
[COREGEN.VHDL Component Instantiation.hist_ram]
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component hist_ram"
text005="    port ("
text006="    addr: IN std_logic_VECTOR(7 downto 0);"
text007="    clk: IN std_logic;"
text008="    din: IN std_logic_VECTOR(31 downto 0);"
text009="    dout: OUT std_logic_VECTOR(31 downto 0);"
text010="    en: IN std_logic;"
text011="    we: IN std_logic);"
text012="end component;"
text013=""
text014=""
text015=""
text016=" "
text017="-------------------------------------------------------------"
text018=" "
text019="-- The following code must appear in the VHDL architecture body."
text020="-- Substitute your own instance name and net names."
text021=" "
text022="your_instance_name : hist_ram"
text023="        port map ("
text024="            addr => addr,"
text025="            clk => clk,"
text026="            din => din,"
text027="            dout => dout,"
text028="            en => en,"
text029="            we => we);"
text030=" "
type=template
[COREGEN.VHDL Component Instantiation.new_gray_table]
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component new_gray_table"
text005="    port ("
text006="    addra: IN std_logic_VECTOR(9 downto 0);"
text007="    addrb: IN std_logic_VECTOR(9 downto 0);"
text008="    clka: IN std_logic;"
text009="    clkb: IN std_logic;"
text010="    dina: IN std_logic_VECTOR(7 downto 0);"
text011="    doutb: OUT std_logic_VECTOR(7 downto 0);"
text012="    wea: IN std_logic);"
text013="end component;"
text014=""
text015=""
text016=""
text017=" "
text018="-------------------------------------------------------------"
text019=" "
text020="-- The following code must appear in the VHDL architecture body."
text021="-- Substitute your own instance name and net names."
text022=" "
text023="your_instance_name : new_gray_table"
text024="        port map ("
text025="            addra => addra,"
text026="            addrb => addrb,"
text027="            clka => clka,"
text028="            clkb => clkb,"
text029="            dina => dina,"
text030="            doutb => doutb,"
text031="            wea => wea);"
text032=" "
type=template
